#pragma once

#include "driver/gpio.h"

#define ROBOT_OLED_WIDTH 128
#define ROBOT_OLED_HEIGHT 64
#define ROBOT_OLED_ADDR_PRIMARY 0x3C
#define ROBOT_OLED_ADDR_SECONDARY 0x3D
#define ROBOT_OLED_SDA_GPIO GPIO_NUM_8
#define ROBOT_OLED_SCL_GPIO GPIO_NUM_9
#define ROBOT_OLED_I2C_PORT I2C_NUM_0
#define ROBOT_OLED_I2C_FREQ_HZ 400000
#define ROBOT_OLED_CMD_BITS 8

#define ROBOT_LF_GPIO GPIO_NUM_0
#define ROBOT_LB_GPIO GPIO_NUM_1
#define ROBOT_RF_GPIO GPIO_NUM_2
#define ROBOT_RB_GPIO GPIO_NUM_3
#define ROBOT_STBY_GPIO GPIO_NUM_10

#define ROBOT_WIFI_AP_SSID "桌面机器人"
#define ROBOT_WIFI_AP_CHANNEL 1
#define ROBOT_WIFI_AP_MAX_CONNECTIONS 4

#define ROBOT_DNS_PORT 53
#define ROBOT_HTTP_PORT 80

typedef enum {
    ROBOT_RANDOM_OFF = 0,
    ROBOT_RANDOM_SOFT,
    ROBOT_RANDOM_NORMAL,
} robot_random_mode_t;
